# Generated by Django 5.1.4 on 2024-12-07 09:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DetailsDB',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=100, null=True)),
                ('description', models.CharField(blank=True, max_length=500, null=True)),
                ('price', models.IntegerField(blank=True, null=True)),
                ('advprice', models.IntegerField(blank=True, null=True)),
                ('roomimage1', models.ImageField(blank=True, null=True, upload_to='Room_images')),
                ('roomimage2', models.ImageField(blank=True, null=True, upload_to='Room_images')),
                ('roomimage3', models.ImageField(blank=True, null=True, upload_to='Room_images')),
            ],
        ),
    ]
